services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-assessment
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/api.Dockerfile
        - action: rebuild
          path: ./backend/uv.lock
        - action: rebuild
          path: ./backend/pyproject.toml
    volumes:
      - ./backend:/app
      - /app/.venv
    environment:
      - PYTHONUNBUFFERED=1
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-assessment
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/Dockerfile
        - action: rebuild
          path: ./frontend/package.json
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    stdin_open: true
    tty: true
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
